version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/hive
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/hive
    steps:
      - run: yarn build
  test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/hive
    steps:
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/hive
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync dist s3://hives-front --delete
      - run:
          name: Invalidate cache
          command: aws cloudfront create-invalidation --distribution-id ET6VOPK1D013Y--paths *
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
