version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/hive
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hive

  dependencies:
    docker:
      - image: circleci/node:latest
    working_directory: ~/hive
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/hive
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/hive
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  deploy:
    docker:
      - image: cibuilds/aws:latest
    working_directory: ~/hive
    steps:
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy to S3
          command: aws s3 sync /home/circleci/hive/dist s3://hives-front --delete
      - run:
          name: Invalidate cache
          command: aws cloudfront create-invalidation --distribution-id ET6VOPK1D013Y --paths *

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - checkout_code
      - dependencies:
          requires:
          - checkout_code
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master
